language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.1
branches:
  only:
    - master    
before_install:
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar
after_success:
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/dotnet-build.sh
  - ./scripts/dotnet-test.sh
# after_success:
#   - ./scripts/dotnet-publish.sh
#   - ./scripts/docker-publish.sh
# notifications:
#   email:
#     on_success: never
#     on_failure: always
